config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/dashboard", to: 'empowerments#dashboard', as: :empowerments_dashboard
  get "myobnb", to: 'users#host_index'

  resources :empowerments do
    get "/activity", to: 'empowerments#new_activity', as: :new_activity
    post "/activity", to: 'empowerments#create_activity', as: :create_activity
  end


  # static pages
  get "/blog", to: 'pages#blog'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empowerment.rb
class Empowerment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_one :empowerment, dependent: :destroy

  after_create :initialize_empowerment

  private

  def initialize_empowerment
    Empowerment.create!(user: self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # include Pundit

  # # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/empowerments_controller.rb
class EmpowermentsController < ApplicationController

  # before_action :find_empowerment

  def dashboard
     @empowerment = current_user.empowerment
  end

  def new_activity
    @empowerment = Empowerment.where(user: current_user)
  end

  def create_activity
    @empowerment = Empowerment.where(user: current_user)
  end

  # private

  # def find_empowerment
  #   @empowerment = current_user.empowerment
  #   # authorize @empowerment
  # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/empowerments/dashboard.html.erb
Hello dashboard
<br>

<%= link_to 'Edit empowerment', edit_empowerment_path(@empowerment), class: 'btn btn-primary'%>

<br>
<%= link_to 'Add new activity', empowerment_new_activity_path(@empowerment), class: 'btn btn-primary'%>

app/views/empowerments/edit.html.erb
hello edit world

app/views/empowerments/new_activity.html.erb
hello new activity

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FeelGoodTwo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1515890435782-59a5bb6ec191?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80');">
  <div class=" d-flex justify-content-center mb-2">
  <%= image_tag "feelgood_logo.png", class: "logo-home banner-content" %>
  </div>
  <div class="banner-content pt-3 pl-5">
    <h1>Make yourself happy again!</h1>
    <p>Train your happiness and love yourself</p>
    <div class="d-flex justify-content-around pb-3">
      <%= link_to 'Signup', new_user_session_path, class:'btn btn-outline-light'%>
      <%= link_to 'Enter', empowerments_dashboard_path, class: 'btn btn-outline-light'%>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag("feelgood_logo.png", :alt => "logo") %>
    <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Activities", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag("buddha.png", :alt => "avatar", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
Hello World